"""Minimal Wavefront OBJ writer — vertices + triangle faces, optional vertex
normals. Pure Python; large meshes write in a few seconds via buffered I/O.

Unity imports OBJ natively: "Assets/Import New Asset…" → drop in the .obj.
Mesh winding is preserved; we emit counter-clockwise triangles so Unity treats
the visible side as the front face.

We deliberately avoid materials (.mtl) and texture coords because the meshes
this stage produces are colliders + lidar-return surfaces, not visual hero
assets. Material assignment happens in Unity per-mesh via the layer manifest.
"""
from __future__ import annotations

import os
from typing import Optional

import numpy as np


def write_obj(path: str,
              vertices: np.ndarray,
              faces: np.ndarray,
              normals: Optional[np.ndarray] = None,
              object_name: str = 'mesh') -> None:
    """Write an OBJ.

    Args:
      path:     output filename (.obj). Parent dir is created.
      vertices: (V, 3) float array of XYZ.
      faces:    (F, 3) int array, 0-based vertex indices forming triangles.
      normals:  optional (V, 3) per-vertex normals; written as `vn` lines.
      object_name: written as `o <name>`. Unity uses this as the GameObject name.
    """
    if vertices.ndim != 2 or vertices.shape[1] != 3:
        raise ValueError(f'vertices must be (V, 3); got {vertices.shape}')
    if faces.ndim != 2 or faces.shape[1] != 3:
        raise ValueError(f'faces must be (F, 3); got {faces.shape}')
    if normals is not None and normals.shape != vertices.shape:
        raise ValueError(f'normals shape {normals.shape} must match vertices {vertices.shape}')
    V = vertices.shape[0]
    if faces.size and (faces.min() < 0 or faces.max() >= V):
        raise ValueError(f'face indices out of range: min={faces.min()} max={faces.max()} V={V}')

    os.makedirs(os.path.dirname(os.path.abspath(path)) or '.', exist_ok=True)

    # Buffer the entire file as one bytes write — much faster than per-line I/O
    # for million-vertex meshes. Use ASCII formatting (.6f keeps mm precision).
    chunks: list[bytes] = []
    chunks.append(f'# OBJ generated by pcd_to_meshes\n'.encode('ascii'))
    chunks.append(f'o {object_name}\n'.encode('ascii'))

    # Vertices
    v = np.asarray(vertices, dtype=np.float64)
    for i in range(V):
        chunks.append(f'v {v[i,0]:.6f} {v[i,1]:.6f} {v[i,2]:.6f}\n'.encode('ascii'))

    # Vertex normals
    if normals is not None:
        n = np.asarray(normals, dtype=np.float64)
        for i in range(V):
            chunks.append(f'vn {n[i,0]:.6f} {n[i,1]:.6f} {n[i,2]:.6f}\n'.encode('ascii'))

    # Faces — OBJ is 1-indexed
    f = np.asarray(faces, dtype=np.int64) + 1
    if normals is None:
        for i in range(f.shape[0]):
            chunks.append(f'f {f[i,0]} {f[i,1]} {f[i,2]}\n'.encode('ascii'))
    else:
        for i in range(f.shape[0]):
            a, b, c = int(f[i,0]), int(f[i,1]), int(f[i,2])
            chunks.append(f'f {a}//{a} {b}//{b} {c}//{c}\n'.encode('ascii'))

    with open(path, 'wb') as fh:
        fh.write(b''.join(chunks))


def estimate_vertex_normals(vertices: np.ndarray, faces: np.ndarray) -> np.ndarray:
    """Average face normals onto vertices. Returns (V, 3) unit normals.

    Cheap and robust. Better than no normals for Unity's auto-shading;
    if you want smoothing groups proper, re-import with smooth-by-angle in
    Unity's import settings."""
    v = np.asarray(vertices, dtype=np.float64)
    f = np.asarray(faces, dtype=np.int64)
    e1 = v[f[:, 1]] - v[f[:, 0]]
    e2 = v[f[:, 2]] - v[f[:, 0]]
    fn = np.cross(e1, e2)
    nrm = np.linalg.norm(fn, axis=1, keepdims=True)
    nrm[nrm == 0] = 1.0
    fn = fn / nrm

    vn = np.zeros_like(v)
    for k in range(3):
        np.add.at(vn, f[:, k], fn)
    nrm = np.linalg.norm(vn, axis=1, keepdims=True)
    nrm[nrm == 0] = 1.0
    return vn / nrm
